### ISSUE TITLE
DLL Injection checks

### ISSUE THREAD

**Issue by friuns2** [LordNoteworthy/al-khaser#145]
Is there ways to detect if malicious dll injected?

**Comment by gsuberland** [comment]
Yes. There are five primary ways to enumerate DLLs that have been loaded into the process:

 * CreateToolHelp32Snapshot with Module32First/Next
 * EnumProcessModules(Ex)
 * Walk the LDR structures manually via the PEB (making sure to get the WOW64 PEB too for 32-bit processes on 64-bit systems)
 * Scan all memory pages with GetModuleHandle (32-bit only, 64-bit would be too slow)
 * Scan all memory pages with VirtualQuery to find executable allocations, then check the start of each allocation for 'MZ' (again 32-bit only for speed reasons).

I'm not sure yet how I can speed up the latter two to make them usable for x64 processes. I'm looking into a few potential ways to enumerate all allocated memory (not just the heaps) in the process but none of it is well documented and I'm mostly having to guess.

Once modules have been identified we can simply look to see if any of them have paths outside the system directory. Validating that they are signed is another potential step but I'd like to avoid it because signing checks are slow and can trigger an outbound network connection for OCSP/CRLs.

Another potential check is to do a compare across these methods to potentially find DLLs that have been loaded into memory but don't appear in the LDR. Furthermore we could try to look for orphaned LDR entries to find modules that have been hidden.

**Comment by gsuberland** [comment]
Work on this has begun in the [dll-injection-detection](https://github.com/LordNoteworthy/al-khaser/tree/dll-injection-detection) branch.
