### ISSUE TITLE
ScyllaHide

### ISSUE THREAD

**Issue by lurumdare** [LordNoteworthy/al-khaser#181]
How to be with her? What checks are effective?

**Comment by lurumdare** [comment]
Tests: https://www49.zippyshare.com/v/SDzuI0W0/file.html

Scyllahide all options. Clean system.

**Comment by lurumdare** [comment]
Only 3 checks effective https://i.imgur.com/wyzMjWv.png

**Comment by gsuberland** [comment]
As we noted in your recent PR, we aren't going to get into an endless arms race with another open source project whose entire point is to bypass our checks. It just results in a lot of wasted effort that could be better spent on coming up with new and novel ways to detect VMs and debuggers.

The primary goal of this project is to test malware analysis VMs, sandboxes, and security product heuristics. The secondary goal of this project is to discover new detection mechanisms that can further the primary goal. We are not interested in providing a set of weaponised heuristic-resistant reference implementations for the detection tricks we discover. This is mostly because it would not further the primary or secondary goals of the project, but also because we don't want to hand weaponised detection-resistant VM/debug detection tricks to malicious actors.

I hope you understand our position on this matter now.

**Comment by lurumdare** [comment]
@gsuberland Yes
