### ISSUE TITLE
psapi is missing in  windows xp

### ISSUE THREAD

**Issue by cattrace** [LordNoteworthy/al-khaser#198]
![image](https://user-images.githubusercontent.com/4670343/72313758-62ab3280-36c7-11ea-9c3d-daad13ae1f2b.png)

**Comment by cattrace** [comment]
compiled env: vs2017;select xp options

**Comment by cetfor** [comment]
Hey @cattrace, it may be worth trying to replace `[EnumProcessModulesEx](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-enumprocessmodulesex)` with `EnumProcessModulesEx`*(https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-enumprocessmodules).  Note the difference in prototype with the inclusion of a `dwFilterFlag` in the `Ex` variant.

I don't believe the `Ex` variant is available on Windows XP, please correct me if I'm wrong.  There could be a Windows version check inside `ScanForModules_EnumProcessModulesEx_Internal` (or a higher level) to dynamically call the correct version for the running platform.

**Comment by LordNoteworthy** [comment]
As @cetfor mentioned,  EnumProcessModulesEx requires Windows Vista+.

And apparently that last parameter of EnumProcessModulesEx is used there, not that we can easily get rid of it. If you want, you need to do the filtering by yourself.

Honestly, at this point, I don't think XP is anymore a target to aim for.

@gsuberland  ?   :)

**Comment by gsuberland** [comment]
It's fair to say that Windows XP isn't _officially_ supported by this project at the moment, since it's so old, but I think wherever possible we should still try to make it at least not crash, even if the check can't run.

While looking into this I discovered that we would actually have not been able to run al-khaser properly on some Windows 7 machines, because they moved `EnumProcessModulesEx` out of psapi into kernel32 for Win7, then back into psapi for Win8. I also discovered that we did not have a manifest file for the project, which caused version checks to return incorrect results.

I'm merging #207 to resolve this.
